language: objective-c
osx_image: xcode10.1
cache:
 - bundler
script:
 - xcodebuild test -project Example/RFIBANHelper.xcodeproj -scheme RFIBANHelper build test -destination platform='iOS Simulator,name=iPhone 7,OS=latest'
 - bundle exec pod lib lint --quick
after_success:
 - bash <(curl -s https://codecov.io/bash)
before_install:
 - gem install -v 2.0.1 bundler
 - bundle _2.0.1_ install
 - brew update
 - brew outdated carthage || brew upgrade carthage
before_deploy:
  - carthage build --no-skip-current
  - carthage archive RFIBANHelper
